
---
services:
  romm-sync:
    build: .
    container_name: romm-sync
    restart: unless-stopped
    env_file: .env.example
    volumes:
      - ${SYNC_FOLDER}:/syncdata:ro  # bind mounts the local library
      - ./data:/appdata
