
---
services:
  romm-sync:
    build: .
    container_name: romm-sync
    restart: unless-stopped
    volumes:
      - ${SYNC_FOLDER}:/syncdata:ro  # bind mounts the local library
      - ./data:/appdata
    networks:
      - dockernetg9
networks:
  dockernetg9:
    external: true
