
---
services:
  romm-sync:
    build: .
    container_name: romm-sync
    restart: unless-stopped
    env_file: .env.example
    volumes:
    # do NOT change the target bind mounts. Specify the directories that are relevant to you.
      # - ${ALL_SYNC_FOLDER}:/syncdata:ro  # Uncomment if saves and states in the same folder.
      - ${SAVE_SYNC_FOLDER}:/syncdata/saves:ro
      - ${STATE_SYNC_FOLDER}:/syncdata/states:ro
      - ./platform_mapping.yaml:/config/platform_mapping.yaml  # do not change the target bind mount or the filename!!
